
banks = ["Сбербанк", "Газпромбанк", "Альфа-Банк", "ВТБ", "Тинькофф", "Райффайзенбанк"]

payment_systems = ["Visa", "MasterCard", "МИР"]

stores = [
    "М.видео",
    "Эльдорадо",
    "Технопарк",
    "DNS",
    "Ситилинк",
    "Мега",
    "РТС",
    "СберМегаМаркет",
    "Технополис",
    "Норд",
    "Леруа Мерлен",
    "Касторама",
    "Техносклад",
    "Компьютерный мир",
    "Склад Услуг",
    "Алло",
    "Гипермаркет Электроники",
    "РТС-полис",
    "Мир Электроники",
    "Электросила",
    "Техника для дома",
    "ПетроЭлектро",
    "КультТехника",
    "Компьютерная Сказка",
    "Электроника24",
    "Технический Рай",
    "Магнит",
    "Сила Техники",
    "Технопланета",
    "ЭкоТехника",
    "Техника Плюс",
    "ХоббиТехника",
    "СуперЭлектроника",
    "ТехноДом",
    "Магазин для Гиков"
]
coordinates = [
    (59.935067, 30.321701),
    (59.935578, 30.335610),
    (59.930384, 30.349496),
    (59.919218, 30.328348),
    (59.933090, 30.332695),
    (59.898034, 30.524110),
    (59.929101, 30.349950),
    (59.918268, 30.354700),
    (59.895752, 30.485174),
    (59.931944, 30.318672),
    (59.887218, 30.275622),
    (59.961893, 30.302962),
    (59.884301, 30.261245),
    (59.956748, 30.304135),
    (59.952005, 30.374380),
    (59.935753, 30.322591),
    (59.867471, 30.303989),
    (59.874816, 30.265236),
    (59.931111, 30.294389),
    (59.914832, 30.307320),
    (59.949960, 30.297554),
    (59.872250, 30.367981),
    (59.932109, 30.321487),
    (59.951050, 30.321650),
    (59.926054, 30.353815),
    (59.939857, 30.379249),
    (59.913070, 30.290614),
    (59.935012, 30.308919),
    (59.907121, 30.361413),
    (59.867844, 30.256433),
    (59.872879, 30.372264),
    (59.897156, 30.296864),
    (59.895790, 30.372575),
    (59.930390, 30.325660),
    (59.916457, 30.339893)
]


categories = ["Смартфоны",
    "Планшеты",
    "Лаптопы",
    "Персональные компьютеры",
    "Мониторы",
    "Телевизоры",
    "Умные часы",
    "Наушники",
    "Аудиосистемы",
    "Bluetooth-колонки",
    "Фотоаппараты",
    "Видеокамеры",
    "Дроны",
    "Игровые консоли",
    "Игровые компьютеры",
    "Периферийные устройства (клавиатуры, мыши)",
    "Принтеры",
    "Сканеры",
    "Проекторы",
    "Холодильники",
    "Стиральные машины",
    "Посудомоечные машины",
    "Микроволновые печи",
    "Тостеры",
    "Блендеры",
    "Кофеварки",
    "Умные колонки",
    "Системы безопасности (камера, датчики)",
    "Умные замки",
    "Домашние кинотеатры",
    "Blu-ray плееры",
    "USB-накопители",
    "Внешние жесткие диски",
    "Сетевые накопители (NAS)",
    "Модемы",
    "Роутеры",
    "Умные лампы",
    "Веб-камеры",
    "Микрофоны",
    "Картриджи для принтеров",
    "Профессиональные видеокамеры",
    "Умные стиральные машины",
    "Умные холодильники",
    "Динамики",
    "Аккумуляторы и зарядные устройства",
    "Электронные книги",
    "Умные калонки",
    "Электросамокаты",
    "Электрические скейтборды",
    "Развлекательные системы для автомобилей",
    "GPS-навигаторы",
    "Автомобильные видеорегистраторы",
    "Аксессуары для мобильных устройств",
    "Пылесосы"]

brands = [ "Apple", "Samsung", "Sony" , "LG", "Panasonic", "Dell", "HP", "Lenovo", "Microsoft", "Asus", "Acer", "Razer", "NVIDIA", "AMD", "Intel", "Google", "Xiaomi", "Huawei", "OnePlus", "Oppo", "Realme", "Vivo", "BlackBerry", "Motorola", "Nokia", "TCL", "ZTE", "Logitech", "Corsair", "Western Digital", "Seagate", "Kingston", "Crucial", "Thermaltake", "Epson", "Brother", "Canon", "Nikon", "Fujifilm", "GoPro", "DJI", "Fitbit", "Garmin", "Bose", "Beats", "JBL", "Sennheiser", "Bang & Olufsen", "Pioneer", "Onkyo", "Yamaha", "Sonos", "Philips", "Toshiba", "Sharp", "Mitsubishi", "NEC", "ViewSonic", "BenQ", "Acer", "MSI", "Gigabyte", "Sapphire", "EVGA", "ASRock", "Razer", "SteelSeries", "HyperX", "Roccat", "Turtle Beach", "XFX", "Alienware", "Origin PC", "Corsair", "NZXT", "Thermaltake", "Cooler Master", "Antec", "Fractal Design", "BitFenix", "Noctua", "Lian Li", "Deepcool", "ARCTIC", "Be Quiet!", "Sabrent", "InWin", "Zalman", "Sharkoon", "Adata", "Patriot", "Silicon Power", "Transcend", "Team Group", "Lexar", "PNY", "Sandisk", "Lexar", "ADATA", "Buffalo", "IOGEAR", "D-Link", "Netgear", "TP-Link", "Linksys", "Belkin", "Zyxel", "TrendNet", "MikroTik", "Ubiquiti", "Palo Alto Networks", "Fortinet", "Sophos", "Cisco", "Juniper Networks", "Arista Networks", "HPE", "Dell EMC", "IBM", "Oracle", "SAP", "Salesforce", "Adobe", "Autodesk", "Intuit", "Microsoft Dynamics", "Zoho", "Shopify", "Magento", "WooCommerce", "BigCommerce", "SquareSpace", "Wix", "GoDaddy", "Bluehost", "HostGator", "SiteGround", "A2 Hosting", "DreamHost", "InMotion Hosting", "Liquid Web", "WP Engine", "Vercel", "Netlify", "Cloudflare", "Amazon", "eBay", "Alibaba", "Etsy", "Rakuten", "Flipkart", "JD.com", "Best Buy", "Newegg", "B&H Photo Video", "Micro Center", "Fry's Electronics", "Walmart", "Target", "Costco", "Sam's Club", "Argos", "Carrefour", "Lidl", "Aldi", "Tesco", "Sainsbury's", "Metro", "Cash & Carry", "Croma", "Cdiscount", "MediaMarkt", "Conforama", "El Corte Inglés", "Fnac", "Darty", "Comet", "Currys", "Maplin", "Poundland", "John Lewis", "Argos", "Kogan", "Jaycar", "Dick Smith", "Anaconda", "Harvey Norman", "The Good Guys", "Officeworks", "Staples", "Office Depot", "Quill", "Grainger", "McMaster-Carr", "Fastenal", "MSC Industrial Direct", "Digi-Key", "Mouser Electronics", "Allied Electronics", "RS Components", "Farnell", "Sourcetronic", "Sourcing Connection", "TME", "Conrad", "Newark", "Arrow Electronics", "Avnet", "Future Electronics", "Component Distributors", "B&B Electronics", "Molex", "TE Connectivity", "Amphenol", "3M", "Honeywell", "Siemens", "Rockwell Automation", "Schneider Electric", "Emerson", "ABB", "GE", "Philips", "Bosch", "Samsung Heavy Industries", "Mitsubishi Electric", "Panasonic", "Kyocera", "Ricoh", "Toshiba", "Canon", "Seiko Epson", "Harman Kardon", "JBL", "Bose", "Sennheiser", "Audio-Technica", "Sony", "Pioneer", "Kenwood", "Alpine", "Kicker", "MTX Audio", "JL Audio", "Rockford Fosgate", "Focal", "Dynaudio", "Bang & Olufsen", "KEF", "Cambridge Audio", "Naim Audio", "Monitor Audio", "Dali", "SVS", "Paradigm", "Definitive Technology", "Polk Audio", "Klipsch", "Bowers & Wilkins", "Sonos", "Bang & Olufsen", "Harman", "Vizio", "TCL", "Hisense", "Skyworth", "Philips", "LG", "Samsung", "Sony", "Sharp", "BenQ", "Epson", "ViewSonic", "Acer", "Dell", "HP", "Lenovo", "Microsoft", "Razer", "Logitech", "Corsair", "HyperX", "SteelSeries", "Cooler Master", "NZXT", "Thermaltake", "Deepcool", "Lian Li", "InWin", "Antec", "BitFenix", "Fractal Design", "Noctua", "ARCTIC", "be quiet!", "Sabrent", "Team Group", "Silicon Power", "Transcend", "Adata", "Patriot", "Lexar", "PNY", "Sandisk", "Buffalo", "IOGEAR", "D-Link", "Netgear", "TP-Link", "Linksys", "Belkin", "Zyxel", "TrendNet", "MikroTik", "Ubiquiti", "Palo Alto Networks", "Fortinet", "Sophos", "Cisco", "Juniper Networks", "Arista Networks", "HPE", "Dell EMC", "IBM", "Oracle", "SAP", "Salesforce", "Adobe", "Autodesk", "Intuit", "Microsoft Dynamics", "Zoho", "Shopify", "Magento", "WooCommerce", "BigCommerce", "SquareSpace", "Wix", "GoDaddy", "Bluehost", "HostGator", "SiteGround", "A2 Hosting", "DreamHost", "InMotion Hosting", "Liquid Web", "WP Engine", "Vercel", "Netlify", "Cloudflare", "Amazon", "eBay", "Alibaba", "Etsy", "Rakuten", "Flipkart", "JD.com", "Best Buy", "Newegg", "B&H Photo Video", "Micro Center", "Fry's Electronics", "Walmart", "Target", "Costco", "Sam's Club", "Argos", "Carrefour", "Lidl", "Aldi", "Tesco", "Sainsbury's", "Metro", "Cash & Carry", "Croma", "Cdiscount", "MediaMarkt", "Conforama", "El Corte Inglés", "Fnac", "Darty", "Comet", "Currys", "Maplin", "Logitech", "Razer", "HyperX", "SteelSeries", "ZOTAC", "EVGA", "MSI", "Gigabyte", "ASRock", "Enermax", "Cooler Master", "NZXT", "Thermaltake", "Antec", "Fractal Design", "Roccat", "Ducky", "Varmilo", "Corsair", "Adata","TP-Link", "Netgear", "Linksys", "D-Link", "Zyxel", "Synology", "QNAP", "Apple", "Samsung", "Microsoft","Amazon", "eBay", "Alibaba", "Etsy", "Walmart", "Best Buy", "Newegg", "Target", "Sears", "Argos"]